In [2]:
import numpy as np

In [2]:
#### Operations on Array

In [4]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [5]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [6]:
a+b ##1+5=6 , 2+6=8, 3+7=10 , 4+8=12

array([[ 6,  8],
       [10, 12]])

In [7]:
a-b

array([[-4, -4],
       [-4, -4]])

In [8]:
## for matrix Multiplication
a.dot(b)

array([[19, 22],
       [43, 50]])

In [9]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [10]:
a**2

array([ 1,  4,  9, 16])

In [11]:
a**3

array([ 1,  8, 27, 64])

In [12]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [13]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [14]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [15]:
# LinSpace() ----> It will return same gap values in a given range .

In [16]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [17]:
# Unique() ----> It will return 3 arrays .
# arr ---> return original values of array .
# return_index = True ----> return return index value of unqie numbers .
# return_counts = True ----> It will return total freqnecy of each unique value .

In [20]:
a = np.array([1,2,3,2,2,2,3,3,2,4,5])
a

array([1, 2, 3, 2, 2, 2, 3, 3, 2, 4, 5])

In [21]:
np.unique(a , return_index=True , return_counts=True)

(array([1, 2, 3, 4, 5]), array([ 0,  1,  2,  9, 10]), array([1, 5, 3, 1, 1]))

In [22]:
# hstack() and vstack()

# hstack() ----> It will add 2 or more arrays in horizontally .
# vstack() ----> It will add 2 or more arrays in vertically.

In [25]:
a = np.arange(1,5).reshape(2,2)
b = np.arange(5,9).reshape(2,2)
c = np.arange(9,13).reshape(2,2)

In [26]:
np.hstack((a,b,c))

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 12]])

In [28]:
np.vstack((a,b,c))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [6]:
# array (30,80) total elements 36 ---> reshape (2*18, 4*9,6*6)

# array ----> [6,10], [11,15] ---> combined horizontally