In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
b = np.array(a)
b

array([1, 2, 3, 4, 5])

In [3]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print("Total ROws and columns:" , b.shape)
print("Total Elements:" , b.size)
print("Total Dimension:" , b.ndim)

Total ROws and columns: (3, 3)
Total Elements: 9
Total Dimension: 2


In [8]:
# Pre-defined Functions in Numpy

In [9]:
# (1). zeros() ----> It will create an array in which all the values are 0 .
a = np.zeros(4)
a

array([0., 0., 0., 0.])

In [10]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# (2). ones() ---> It will create an array in which all the values are 1 .
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [12]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# (3). eye() ----> It will create an array in which digonal positional elements are 1 and rest all
# are 0.

In [14]:
a = np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# (4). diag() ----> It will set our custm values on digonal position .
a = np.array([1,45,78,90])
a

array([ 1, 45, 78, 90])

In [16]:
b = np.diag(a)
b

array([[ 1,  0,  0,  0],
       [ 0, 45,  0,  0],
       [ 0,  0, 78,  0],
       [ 0,  0,  0, 90]])

In [17]:
# (5). Random Module
# (a). Randint() ---> It will create random numbers in a given range .
# sytax: np.random.randint(min_range , max_range , total_numbers)

In [25]:
a = np.random.randint(1,10,3)
a

array([8, 6, 6])

In [23]:
# (b). Rand() ---> It will create random numbers in range 0-1/

In [24]:
a = np.random.rand(5)
a

array([0.32967831, 0.64096086, 0.14768652, 0.47287573, 0.19129836])

In [26]:
# (c). seed() ----> It will fix our random generated data .

In [42]:
np.random.seed(3)
a = np.random.randint(1,10,3)
a

array([9, 4, 9])

In [43]:
# View Vs Copy

# View means modification in original data and copy means changes in duplicate data will not reflect
# the original data .

In [44]:
a = np.array([10,20,30,40,50,60,70,80])
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [47]:
a[3:6] = 0

In [48]:
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [49]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6].copy()
b[:] = 0
b

array([0, 0, 0])

In [50]:
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [51]:
# Operation on Array

In [52]:
# (1). arange() -----> It will works as as for loop in numpy .

In [57]:
a = np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [58]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [59]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [62]:
b = a%2== 0

In [63]:
a[b]

array([ 2,  4,  6,  8, 10, 12, 14])

In [64]:
# Reshaping condition
# n(rows) * n(columns) = n(total_elements)

In [65]:
# total ememtns = 12
# 1*12 , 12*1
# 2*6 , 6*2
# 3*4 , 4*3


In [66]:
a = np.random.randint(1,50,12)
a

array([ 9,  1, 22, 20, 11, 44, 42, 11, 22, 39, 33, 21])

In [67]:
a.reshape(2,6)

array([[ 9,  1, 22, 20, 11, 44],
       [42, 11, 22, 39, 33, 21]])

In [68]:
a.reshape(3,4)

array([[ 9,  1, 22, 20],
       [11, 44, 42, 11],
       [22, 39, 33, 21]])

In [70]:
# a.reshape(3,5)

In [75]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [76]:
b = np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [77]:
a+b

array([[ 6,  8],
       [10, 12]])

In [78]:
a-b

array([[-4, -4],
       [-4, -4]])

In [79]:
a*b   ### Not matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [80]:
a.dot(b)   ### Matrix multiplication

array([[19, 22],
       [43, 50]])

In [81]:
a

array([[1, 2],
       [3, 4]])

In [82]:
b

array([[5, 6],
       [7, 8]])